name: Build artifact for app1
on: 
  push:
    branches: [main]
jobs:
  build_deployment_artifact:
    name: app1_deployment_artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          sparse-checkout: |
            admin/app1
            admin/helpers
      - run: |
          mkdir release
          cp -r admin/app1/. release
          cp -r admin/helpers release/scripts
      - uses: actions/upload-artifact@v4
        with: 
          name: app1-release
          path: release
        
          